# CustomFishing does not contain an enchantment system but it's able to read enchantments from items and customize its bonus!
# Vanilla enchants
minecraft:luck_of_the_sea:
  #levels
  1:
    effect:
      weight-add:
        silver: 2
        gold: 1
  2:
    effect:
      weight-add:
        silver: 3
        gold: 2
  3:
    effect:
      weight-add:
        silver: 4
        gold: 3
  4:
    effect:
      weight-add:
        silver: 6
        gold: 5
    # https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customfishing/requirements
    requirements:
      permission: luck_of_the_sea.admin

# lucky_catch from EcoEnchants
eco:lucky_catch:
  1:
    effect:
      double-loot: 0.1
  2:
    effect:
      double-loot: 0.2
  3:
    effect:
      double-loot: 0.3

# You can register an enchantment in EcoEnchants called "easy_catch"
# And then create its effects in CustomFishing!
eco:easy_catch:
  1:
    effect:
      difficulty: -1
  2:
    effect:
      difficulty: -2

# AdvancedEnchantments support
AE:lucky:
  1:
    effect:
      double-loot: 0.1
  2:
    effect:
      double-loot: 0.2
  3:
    effect:
      double-loot: 0.3