# don't change
config-version: '9'


lang: en


integration:
  # Skill-xp
  mcMMO: false
  MMOCore: false
  AureliumSkills: false
  EcoSkills: false
  JobsReborn: false
  # Season condition
  CustomCrops: false
  RealisticSeasons: false


worlds:
  # Mode: whitelist/blacklist
  mode: whitelist
  list:
    - world
    - world_nether


mechanics:

  other-loots:

    # Should other loots have the same fishing mechanic CustomFishing provides
    fishing-bar: true

    vanilla:
      # Vanilla loot is available only when 'double-reel-in' is true
      enable: true
      # 0.4 means 40% of the loots are from vanilla
      # and 60% are from CustomFishing Loot system
      ratio: 0.4

    mcMMO:
      # mcMMO treasure system
      # chance represents the chance to try to be a mcMMO treasure
      # But it doesn't mean 50% chance of the loot would be mcMMO treasure
      # mcMMO has a complex treasure system
      enable: false
      chance: 0.5

  # The same to vanilla (refer to the wiki)
  # https://technical-minecraft.fandom.com/wiki/Fishing
  need-open-water: false

  need-special-rod:
    # Players must use rods with CustomFishing's NBT Tags to get loots in CustomFishing but they can experience the special fishing mechanic.
    for-loots: false
    # Players must use rods with CustomFishing's NBT Tags to experience the special fishing mechanic. Otherwise they can only fish in a vanilla way
    to-fish: false

  # does rod lose durability when player successfully fish
  rod-lose-durability: true

  # Cool down time of fish finder(ms)
  fishfinder-cooldown: 3000

  # Competition
  fishing-competition:
    enable: true
    redis: false

  # Fishing bag is a place where players can store their baits, utils, rods (Fish optional)
  fishing-bag:
    enable: true
    # This would add additional NBT Tags to the fish
    can-store-fish: false
    # File/SQLite/MySql
    data-storage-mode: File

  lava-fishing:
    # ticks
    min-time: 100
    max-time: 600


titles:
  success:
    title:
      - '<green>Success!</green>'
      - '<green>GG!</green>'
      - '<green>Good Job!</green>'
    subtitle:
      - 'You have captured a {loot}'
      - 'Hi Harm Hi {loot} Here we go!'
    fade:
      # ticks
      in: 10
      stay: 30
      out: 10
  failure:
    title:
      - '<red>Real food!</red>'
      - '<red>Failure!</red>'
      - '<red>Try next time!</red>'
    subtitle:
      - 'The fish escaped'
      - 'Pay more attention on it!'
    fade:
      in: 10
      stay: 30
      out: 10



other-settings:

  # MONITOR HIGHEST HIGH NORMAL LOW LOWEST
  event-priority: NORMAL

  # If enabled, players would not be able to get job exp in vanilla way
  disable-JobsReborn-fishing-exp: false

  # Convert MMOItems' rod into CustomFishing's rod
  # keep the same key name both in MMOItems and CustomFishing so rods can extend the bonus of those in CustomFishing
  convert-MMOItems-rods: false

  # Prevent other players to pick up your fishing loot
  # This is useful for players to fish in a public area
  prevent-other-players-pick-up-loot: false