# MySQL settings
MySQL:
  host: localhost
  port: 3306
  user: root
  password: password
  database: minecraft
  table-name: customfishing_data
  property:
    use-ssl: false
    encoding: utf8
    timezone: ''
    allowPublicKeyRetrieval: false
  # Connection pool settings
  Pool-Settings:
    enable: false
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 180000
    idle-timeout: 60000

# Redis server
# Sync competition scores between servers without lag!
Redis:
  host: localhost
  port: 6379
  MaxTotal: 10
  MaxIdle: 10
  MinIdle: 1
  MaxWaitMillis: 30000
  MinEvictableIdleTimeMillis: 1800000