name: CustomFishing
version: '${version}'
main: net.momirealms.customfishing.CustomFishing
api-version: 1.17
authors: [ XiaoMoMi ]
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - WorldGuard
  - mcMMO
  - AureliumSkills
  - MMOCore
  - EcoSkills
  - EcoEnchants
  - RealisticSeasons
  - CustomCrops
  - ItemsAdder
  - Oraxen
  - MMOItems
  - eco
  - Jobs
  - Vault

commands:
  customfishing:
    usage: /customfishing
    description: main command
    permission: customfishing.admin
    aliases:
      - cfishing
  fishingbag:
    usage: /fishingbag open
    description: fishing bag command
    permission: customfishing.fishingbag
  sellfish:
    usage: /sellfish
    description: fishing bag command
    permission: customfishing.sellfish

permissions:
  customfishing.*:
    description: Gives access to all customfishing commands
    children:
      customfishing.admin: true
      customfishing.fishingbag: true
      customfishing.sellfish: true

  customfishing.admin:
    default: op
  customfishing.fishingbag:
    default: true
  customfishing.sellfish:
    default: true