skeletalknight:

  enable: true

  # MythicMobsID
  mobID: SkeletalKnight

  # The level of the mob
  level: 0

  # Name is what to show in fish finder
  name: skeletalknight

  # This decides how mythic mob spawn
  vector:
    horizontal: 1.1
    vertical: 1.2

  group: creature
  weight: 10

  requirements:
    weather:
      - thunder
    world:
      - world